language: php

dist: trusty
sudo: false

cache:
  directories:
  - $HOME/.composer/cache
  - .phpunit
  - vendor/

env:
  global:
  - MIN_PHP=7.1.3
  - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
  - php: 7.1.3
    env: deps=high
  - php: 7.2
    env: deps=low

before_install:
# Install Composer and project dependencies.
- curl -sS https://getcomposer.org/installer | php

install:
# Install Composer and project dependencies.
- composer install --optimize-autoloader

script:
# this checks that the composer.json and composer.lock files are valid
- composer validate --strict

# run symfony tests
- php vendor/bin/simple-phpunit

# this checks that the source code follows the Symfony Code Syntax rules
- ./vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no

notifications:
  email:
    on_success: never
    on_failure: always
